///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxSampleParameter.Recording_modules.Database
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InsertFirstName recording.
    /// </summary>
    [TestModule("af17c2bd-631c-47c0-8292-c6bcd11d8795", ModuleType.Recording, 1)]
    public partial class InsertFirstName : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RxSampleParameter.RxSampleParameterRepository repository.
        /// </summary>
        public static global::RxSampleParameter.RxSampleParameterRepository repo = global::RxSampleParameter.RxSampleParameterRepository.Instance;

        static InsertFirstName instance = new InsertFirstName();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InsertFirstName()
        {
            varFirstName = "John";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InsertFirstName Instance
        {
            get { return instance; }
        }

#region Variables

        string _varFirstName;

        /// <summary>
        /// Gets or sets the value of variable varFirstName.
        /// </summary>
        [TestVariable("b876d13a-0bc1-477a-a49c-34f90e02ed4e")]
        public string varFirstName
        {
            get { return _varFirstName; }
            set { _varFirstName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DatabaseTest.FirstName' at 65;9.", repo.ApplicationUnderTest.DatabaseTest.FirstNameInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.DatabaseTest.FirstName.Click("65;9");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varFirstName' with focus on 'ApplicationUnderTest.DatabaseTest.FirstName'.", repo.ApplicationUnderTest.DatabaseTest.FirstNameInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.DatabaseTest.FirstName.PressKeys(varFirstName);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
