///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxSampleParameter.Recording_modules.Database
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InsertLastName recording.
    /// </summary>
    [TestModule("35bd85fd-fb5e-4244-afad-fc536942fdd4", ModuleType.Recording, 1)]
    public partial class InsertLastName : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RxSampleParameter.RxSampleParameterRepository repository.
        /// </summary>
        public static global::RxSampleParameter.RxSampleParameterRepository repo = global::RxSampleParameter.RxSampleParameterRepository.Instance;

        static InsertLastName instance = new InsertLastName();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InsertLastName()
        {
            varLastName = "Public";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InsertLastName Instance
        {
            get { return instance; }
        }

#region Variables

        string _varLastName;

        /// <summary>
        /// Gets or sets the value of variable varLastName.
        /// </summary>
        [TestVariable("14106c13-cdd4-4264-ae0a-09f928b0edba")]
        public string varLastName
        {
            get { return _varLastName; }
            set { _varLastName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DatabaseTest.LastName' at 37;9.", repo.ApplicationUnderTest.DatabaseTest.LastNameInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.DatabaseTest.LastName.Click("37;9");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varLastName' with focus on 'ApplicationUnderTest.DatabaseTest.LastName'.", repo.ApplicationUnderTest.DatabaseTest.LastNameInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.DatabaseTest.LastName.PressKeys(varLastName);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
