///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxSampleParameter.Recording_modules.Database
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SelectDepartment recording.
    /// </summary>
    [TestModule("4eecf895-475c-4594-85aa-3beb655fee3c", ModuleType.Recording, 1)]
    public partial class SelectDepartment : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RxSampleParameter.RxSampleParameterRepository repository.
        /// </summary>
        public static global::RxSampleParameter.RxSampleParameterRepository repo = global::RxSampleParameter.RxSampleParameterRepository.Instance;

        static SelectDepartment instance = new SelectDepartment();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SelectDepartment()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SelectDepartment Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varDepartment.
        /// </summary>
        [TestVariable("53ba3efc-0d86-4571-8fa1-607c3825c48c")]
        public string varDepartment
        {
            get { return repo.varDepartment; }
            set { repo.varDepartment = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DatabaseTest.BtnDepartmentList' at 8;8.", repo.ApplicationUnderTest.DatabaseTest.BtnDepartmentListInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.DatabaseTest.BtnDepartmentList.Click("8;8");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'DepartmentList.SelectDepartment' at Center.", repo.DepartmentList.SelectDepartmentInfo, new RecordItemIndex(1));
            repo.DepartmentList.SelectDepartment.Click();
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
