///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RxSampleParameter.Recording_modules.Database
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SelectGender recording.
    /// </summary>
    [TestModule("e69fe376-7423-43a1-9f46-f9a03375b285", ModuleType.Recording, 1)]
    public partial class SelectGender : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RxSampleParameter.RxSampleParameterRepository repository.
        /// </summary>
        public static global::RxSampleParameter.RxSampleParameterRepository repo = global::RxSampleParameter.RxSampleParameterRepository.Instance;

        static SelectGender instance = new SelectGender();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SelectGender()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SelectGender Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varGender.
        /// </summary>
        [TestVariable("e500bf97-799e-4e83-bda7-fc035d8125cd")]
        public string varGender
        {
            get { return repo.varGender; }
            set { repo.varGender = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.DatabaseTest.SelectGender' at 7;13.", repo.ApplicationUnderTest.DatabaseTest.SelectGenderInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.DatabaseTest.SelectGender.Click("7;13");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
