///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest7
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest7Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("e23bd683-5026-4dc2-859f-7a022d8cdd9b")]
    public partial class MyTest7Repository : RepoGenBaseFolder
    {
        static MyTest7Repository instance = new MyTest7Repository();

        /// <summary>
        /// Gets the singleton class instance representing the MyTest7Repository element repository.
        /// </summary>
        [RepositoryFolder("e23bd683-5026-4dc2-859f-7a022d8cdd9b")]
        public static MyTest7Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest7Repository() 
            : base("MyTest7Repository", "/", null, 0, false, "e23bd683-5026-4dc2-859f-7a022d8cdd9b", ".\\RepositoryImages\\MyTest7Repositorye23bd683.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e23bd683-5026-4dc2-859f-7a022d8cdd9b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest7RepositoryFolders
    {
    }
#pragma warning restore 0436
}
