///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RxDatabase
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RxDatabaseRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("7ed330c8-5668-4cfa-9ca9-402c4c23b7e2")]
    public partial class RxDatabaseRepository : RepoGenBaseFolder
    {
        static RxDatabaseRepository instance = new RxDatabaseRepository();
        RxDatabaseRepositoryFolders.DemoApplicationAppFolder _demoapplication;
        RxDatabaseRepositoryFolders.DepartmentListAppFolder _departmentlist;

        /// <summary>
        /// Gets the singleton class instance representing the RxDatabaseRepository element repository.
        /// </summary>
        [RepositoryFolder("7ed330c8-5668-4cfa-9ca9-402c4c23b7e2")]
        public static RxDatabaseRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RxDatabaseRepository() 
            : base("RxDatabaseRepository", "/", null, 0, false, "7ed330c8-5668-4cfa-9ca9-402c4c23b7e2", ".\\RepositoryImages\\RxDatabaseRepository7ed330c8.rximgres")
        {
            _demoapplication = new RxDatabaseRepositoryFolders.DemoApplicationAppFolder(this);
            _departmentlist = new RxDatabaseRepositoryFolders.DepartmentListAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("7ed330c8-5668-4cfa-9ca9-402c4c23b7e2")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The DemoApplication folder.
        /// </summary>
        [RepositoryFolder("90b14745-bf25-4b07-9bb2-d31f69970826")]
        public virtual RxDatabaseRepositoryFolders.DemoApplicationAppFolder DemoApplication
        {
            get { return _demoapplication; }
        }

        /// <summary>
        /// The DepartmentList folder.
        /// </summary>
        [RepositoryFolder("57208867-ed11-4ec8-924b-0dc686980a77")]
        public virtual RxDatabaseRepositoryFolders.DepartmentListAppFolder DepartmentList
        {
            get { return _departmentlist; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RxDatabaseRepositoryFolders
    {
        /// <summary>
        /// The DemoApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("90b14745-bf25-4b07-9bb2-d31f69970826")]
        public partial class DemoApplicationAppFolder : RepoGenBaseFolder
        {
            RxDatabaseRepositoryFolders.DatabaseTabFolder _databasetab;
            RepoItemInfo _databaseInfo;
            RepoItemInfo _btnexitInfo;

            /// <summary>
            /// Creates a new DemoApplication  folder.
            /// </summary>
            public DemoApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DemoApplication", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "90b14745-bf25-4b07-9bb2-d31f69970826", "")
            {
                _databasetab = new RxDatabaseRepositoryFolders.DatabaseTabFolder(this);
                _databaseInfo = new RepoItemInfo(this, "Database", "?/?/tabpage[@accessiblename='Test database']", "", 30000, null, "34b9f228-153b-44b4-ae34-1e2747592b0f");
                _btnexitInfo = new RepoItemInfo(this, "BtnExit", "button[@controlname='RxButtonExit']", "", 30000, null, "02058d54-efaf-4a1d-b09d-9d7d8538364d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("90b14745-bf25-4b07-9bb2-d31f69970826")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("90b14745-bf25-4b07-9bb2-d31f69970826")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Database item.
            /// </summary>
            [RepositoryItem("34b9f228-153b-44b4-ae34-1e2747592b0f")]
            public virtual Ranorex.TabPage Database
            {
                get
                {
                    return _databaseInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Database item info.
            /// </summary>
            [RepositoryItemInfo("34b9f228-153b-44b4-ae34-1e2747592b0f")]
            public virtual RepoItemInfo DatabaseInfo
            {
                get
                {
                    return _databaseInfo;
                }
            }

            /// <summary>
            /// The BtnExit item.
            /// </summary>
            [RepositoryItem("02058d54-efaf-4a1d-b09d-9d7d8538364d")]
            public virtual Ranorex.Button BtnExit
            {
                get
                {
                    return _btnexitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnExit item info.
            /// </summary>
            [RepositoryItemInfo("02058d54-efaf-4a1d-b09d-9d7d8538364d")]
            public virtual RepoItemInfo BtnExitInfo
            {
                get
                {
                    return _btnexitInfo;
                }
            }

            /// <summary>
            /// The DatabaseTab folder.
            /// </summary>
            [RepositoryFolder("6634980e-930f-41f9-a6d0-229595c55fed")]
            public virtual RxDatabaseRepositoryFolders.DatabaseTabFolder DatabaseTab
            {
                get { return _databasetab; }
            }
        }

        /// <summary>
        /// The DatabaseTabFolder folder.
        /// </summary>
        [RepositoryFolder("6634980e-930f-41f9-a6d0-229595c55fed")]
        public partial class DatabaseTabFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _ageInfo;
            RepoItemInfo _selectmaleInfo;
            RepoItemInfo _btndepartmentlistInfo;
            RepoItemInfo _btnaddentryInfo;
            RepoItemInfo _counterentriesInfo;

            /// <summary>
            /// Creates a new DatabaseTab  folder.
            /// </summary>
            public DatabaseTabFolder(RepoGenBaseFolder parentFolder) :
                    base("DatabaseTab", "?/?/tabpage[@controlname='RxTabStandard']", parentFolder, 30000, null, false, "6634980e-930f-41f9-a6d0-229595c55fed", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First name']", "", 30000, null, "cdb32e2f-3a94-4215-a4ce-eb4b5d575b1b");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last name']", "", 30000, null, "ee66a06e-163b-42b6-8abc-248006bf88ab");
                _ageInfo = new RepoItemInfo(this, "Age", "?/?/text[@controlname='upDownEdit']", "", 30000, null, "305b1e85-498e-4d07-9051-6cd79362827e");
                _selectmaleInfo = new RepoItemInfo(this, "SelectMale", "?/?/radiobutton[@controlname='rdbMale']", "", 30000, null, "a47a714c-11a3-4925-b181-0c2445fd1e45");
                _btndepartmentlistInfo = new RepoItemInfo(this, "BtnDepartmentList", "combobox[@controlname='cmbDepartment']/button", "", 30000, null, "33397b0b-43c6-4daa-99a2-c7853656f16f");
                _btnaddentryInfo = new RepoItemInfo(this, "BtnAddEntry", "button[@controlname='btnAddPerson']", "", 30000, null, "0716c660-ce8c-4fb8-a033-a58ae01bc4fa");
                _counterentriesInfo = new RepoItemInfo(this, "CounterEntries", "text[@controlname='lblNumberOfPersonsNumber']", "", 30000, null, "2580fade-1b69-498e-a86e-74c7c8e8be71");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6634980e-930f-41f9-a6d0-229595c55fed")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6634980e-930f-41f9-a6d0-229595c55fed")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("cdb32e2f-3a94-4215-a4ce-eb4b5d575b1b")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("cdb32e2f-3a94-4215-a4ce-eb4b5d575b1b")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("ee66a06e-163b-42b6-8abc-248006bf88ab")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("ee66a06e-163b-42b6-8abc-248006bf88ab")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Age item.
            /// </summary>
            [RepositoryItem("305b1e85-498e-4d07-9051-6cd79362827e")]
            public virtual Ranorex.Text Age
            {
                get
                {
                    return _ageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Age item info.
            /// </summary>
            [RepositoryItemInfo("305b1e85-498e-4d07-9051-6cd79362827e")]
            public virtual RepoItemInfo AgeInfo
            {
                get
                {
                    return _ageInfo;
                }
            }

            /// <summary>
            /// The SelectMale item.
            /// </summary>
            [RepositoryItem("a47a714c-11a3-4925-b181-0c2445fd1e45")]
            public virtual Ranorex.RadioButton SelectMale
            {
                get
                {
                    return _selectmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The SelectMale item info.
            /// </summary>
            [RepositoryItemInfo("a47a714c-11a3-4925-b181-0c2445fd1e45")]
            public virtual RepoItemInfo SelectMaleInfo
            {
                get
                {
                    return _selectmaleInfo;
                }
            }

            /// <summary>
            /// The BtnDepartmentList item.
            /// </summary>
            [RepositoryItem("33397b0b-43c6-4daa-99a2-c7853656f16f")]
            public virtual Ranorex.Button BtnDepartmentList
            {
                get
                {
                    return _btndepartmentlistInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnDepartmentList item info.
            /// </summary>
            [RepositoryItemInfo("33397b0b-43c6-4daa-99a2-c7853656f16f")]
            public virtual RepoItemInfo BtnDepartmentListInfo
            {
                get
                {
                    return _btndepartmentlistInfo;
                }
            }

            /// <summary>
            /// The BtnAddEntry item.
            /// </summary>
            [RepositoryItem("0716c660-ce8c-4fb8-a033-a58ae01bc4fa")]
            public virtual Ranorex.Button BtnAddEntry
            {
                get
                {
                    return _btnaddentryInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnAddEntry item info.
            /// </summary>
            [RepositoryItemInfo("0716c660-ce8c-4fb8-a033-a58ae01bc4fa")]
            public virtual RepoItemInfo BtnAddEntryInfo
            {
                get
                {
                    return _btnaddentryInfo;
                }
            }

            /// <summary>
            /// The CounterEntries item.
            /// </summary>
            [RepositoryItem("2580fade-1b69-498e-a86e-74c7c8e8be71")]
            public virtual Ranorex.Text CounterEntries
            {
                get
                {
                    return _counterentriesInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CounterEntries item info.
            /// </summary>
            [RepositoryItemInfo("2580fade-1b69-498e-a86e-74c7c8e8be71")]
            public virtual RepoItemInfo CounterEntriesInfo
            {
                get
                {
                    return _counterentriesInfo;
                }
            }
        }

        /// <summary>
        /// The DepartmentListAppFolder folder.
        /// </summary>
        [RepositoryFolder("57208867-ed11-4ec8-924b-0dc686980a77")]
        public partial class DepartmentListAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _projectmanagementInfo;

            /// <summary>
            /// Creates a new DepartmentList  folder.
            /// </summary>
            public DepartmentListAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DepartmentList", "/list[@controlid='1000']", parentFolder, 30000, null, true, "57208867-ed11-4ec8-924b-0dc686980a77", "")
            {
                _projectmanagementInfo = new RepoItemInfo(this, "ProjectManagement", "listitem[@text='Project Management']", "", 30000, null, "b32a1d4e-4dd5-4fee-b85a-452aaf6b98c3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("57208867-ed11-4ec8-924b-0dc686980a77")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("57208867-ed11-4ec8-924b-0dc686980a77")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ProjectManagement item.
            /// </summary>
            [RepositoryItem("b32a1d4e-4dd5-4fee-b85a-452aaf6b98c3")]
            public virtual Ranorex.ListItem ProjectManagement
            {
                get
                {
                    return _projectmanagementInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ProjectManagement item info.
            /// </summary>
            [RepositoryItemInfo("b32a1d4e-4dd5-4fee-b85a-452aaf6b98c3")]
            public virtual RepoItemInfo ProjectManagementInfo
            {
                get
                {
                    return _projectmanagementInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
