///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RxSampleParameter
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RxSampleParameterRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("3c22921b-dd59-4ba6-ab73-142b0267cf40")]
    public partial class RxSampleParameterRepository : RepoGenBaseFolder
    {
        static RxSampleParameterRepository instance = new RxSampleParameterRepository();
        RxSampleParameterRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        RxSampleParameterRepositoryFolders.DepartmentListAppFolder _departmentlist;

        /// <summary>
        /// Gets the singleton class instance representing the RxSampleParameterRepository element repository.
        /// </summary>
        [RepositoryFolder("3c22921b-dd59-4ba6-ab73-142b0267cf40")]
        public static RxSampleParameterRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RxSampleParameterRepository() 
            : base("RxSampleParameterRepository", "/", null, 0, false, "3c22921b-dd59-4ba6-ab73-142b0267cf40", ".\\RepositoryImages\\RxSampleParameterRepository3c22921b.rximgres")
        {
            _applicationundertest = new RxSampleParameterRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _departmentlist = new RxSampleParameterRepositoryFolders.DepartmentListAppFolder(this);
        }

#region Variables

        string _varDepartment = "Project Management";

        /// <summary>
        /// Gets or sets the value of variable varDepartment.
        /// </summary>
        [TestVariable("53ba3efc-0d86-4571-8fa1-607c3825c48c")]
        public string varDepartment
        {
            get { return _varDepartment; }
            set { _varDepartment = value; }
        }

        string _varGender = "Male";

        /// <summary>
        /// Gets or sets the value of variable varGender.
        /// </summary>
        [TestVariable("e500bf97-799e-4e83-bda7-fc035d8125cd")]
        public string varGender
        {
            get { return _varGender; }
            set { _varGender = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3c22921b-dd59-4ba6-ab73-142b0267cf40")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("b5117565-9dfa-49ef-b1ba-11bf744f9e7e")]
        public virtual RxSampleParameterRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The DepartmentList folder.
        /// </summary>
        [RepositoryFolder("1e8b078d-8f4f-4f00-8d6c-712330c43341")]
        public virtual RxSampleParameterRepositoryFolders.DepartmentListAppFolder DepartmentList
        {
            get { return _departmentlist; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RxSampleParameterRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("b5117565-9dfa-49ef-b1ba-11bf744f9e7e")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RxSampleParameterRepositoryFolders.DatabaseTestFolder _databasetest;
            RepoItemInfo _selectdatabaseInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/form[@processname='RxDemoApp']", parentFolder, 30000, null, true, "b5117565-9dfa-49ef-b1ba-11bf744f9e7e", "")
            {
                _databasetest = new RxSampleParameterRepositoryFolders.DatabaseTestFolder(this);
                _selectdatabaseInfo = new RepoItemInfo(this, "SelectDatabase", "?/?/tabpage[@accessiblename='Test database']", "", 30000, null, "732f855f-87c2-4bf6-9d4e-048c6e96bc11");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b5117565-9dfa-49ef-b1ba-11bf744f9e7e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b5117565-9dfa-49ef-b1ba-11bf744f9e7e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SelectDatabase item.
            /// </summary>
            [RepositoryItem("732f855f-87c2-4bf6-9d4e-048c6e96bc11")]
            public virtual Ranorex.TabPage SelectDatabase
            {
                get
                {
                    return _selectdatabaseInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The SelectDatabase item info.
            /// </summary>
            [RepositoryItemInfo("732f855f-87c2-4bf6-9d4e-048c6e96bc11")]
            public virtual RepoItemInfo SelectDatabaseInfo
            {
                get
                {
                    return _selectdatabaseInfo;
                }
            }

            /// <summary>
            /// The DatabaseTest folder.
            /// </summary>
            [RepositoryFolder("bd4be954-a02b-42e5-9938-a41f88eecf3f")]
            public virtual RxSampleParameterRepositoryFolders.DatabaseTestFolder DatabaseTest
            {
                get { return _databasetest; }
            }
        }

        /// <summary>
        /// The DatabaseTestFolder folder.
        /// </summary>
        [RepositoryFolder("bd4be954-a02b-42e5-9938-a41f88eecf3f")]
        public partial class DatabaseTestFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btndepartmentlistInfo;
            RepoItemInfo _btndeletepersonInfo;
            RepoItemInfo _btnaddpersonInfo;
            RepoItemInfo _selectgenderInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _ageInfo;
            RepoItemInfo _txttopdbentryInfo;
            RepoItemInfo _db_counterInfo;

            /// <summary>
            /// Creates a new DatabaseTest  folder.
            /// </summary>
            public DatabaseTestFolder(RepoGenBaseFolder parentFolder) :
                    base("DatabaseTest", "?/?/tabpage[@controlname='RxTabStandard']", parentFolder, 30000, null, false, "bd4be954-a02b-42e5-9938-a41f88eecf3f", "")
            {
                _btndepartmentlistInfo = new RepoItemInfo(this, "BtnDepartmentList", "?/?/button[@accessiblename='Open']", "", 30000, null, "bff6953a-1a5c-478e-b243-8c77b958e7de");
                _btndeletepersonInfo = new RepoItemInfo(this, "BtnDeletePerson", "button[@controlname='btnDeletePerson']", "", 30000, null, "957e2920-0bcb-4736-bee2-f9f870d01a77");
                _btnaddpersonInfo = new RepoItemInfo(this, "BtnAddPerson", "button[@controlname='btnAddPerson']", "", 30000, null, "c4722e95-d82d-4899-a215-558b3ac87145");
                _selectgenderInfo = new RepoItemInfo(this, "SelectGender", "?/?/radiobutton[@controltext=$varGender]", "", 30000, null, "4f1e9f80-1ccf-434f-94d2-71ba10c667f3");
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First name']", "", 30000, null, "d1cabd3d-c174-4f6b-9162-92da0f9715e8");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last name']", "", 30000, null, "1f2fb46b-183a-4669-844d-5111d39a7bc0");
                _ageInfo = new RepoItemInfo(this, "Age", "?/?/text[@controlname='upDownEdit']", "", 30000, null, "888b637e-5f7c-412f-b242-861ad471471e");
                _txttopdbentryInfo = new RepoItemInfo(this, "TxtTopDBEntry", "list[@controlname='lstPersonList']/?/?/listitem", "", 30000, null, "7ea59416-18ba-4fbc-afe2-fbc54a8bab71");
                _db_counterInfo = new RepoItemInfo(this, "DB_Counter", "text[@controlname='lblNumberOfPersonsNumber']", "", 30000, null, "b7165316-6e00-4cbf-946f-533a28fdf096");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bd4be954-a02b-42e5-9938-a41f88eecf3f")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bd4be954-a02b-42e5-9938-a41f88eecf3f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BtnDepartmentList item.
            /// </summary>
            [RepositoryItem("bff6953a-1a5c-478e-b243-8c77b958e7de")]
            public virtual Ranorex.Button BtnDepartmentList
            {
                get
                {
                    return _btndepartmentlistInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnDepartmentList item info.
            /// </summary>
            [RepositoryItemInfo("bff6953a-1a5c-478e-b243-8c77b958e7de")]
            public virtual RepoItemInfo BtnDepartmentListInfo
            {
                get
                {
                    return _btndepartmentlistInfo;
                }
            }

            /// <summary>
            /// The BtnDeletePerson item.
            /// </summary>
            [RepositoryItem("957e2920-0bcb-4736-bee2-f9f870d01a77")]
            public virtual Ranorex.Button BtnDeletePerson
            {
                get
                {
                    return _btndeletepersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnDeletePerson item info.
            /// </summary>
            [RepositoryItemInfo("957e2920-0bcb-4736-bee2-f9f870d01a77")]
            public virtual RepoItemInfo BtnDeletePersonInfo
            {
                get
                {
                    return _btndeletepersonInfo;
                }
            }

            /// <summary>
            /// The BtnAddPerson item.
            /// </summary>
            [RepositoryItem("c4722e95-d82d-4899-a215-558b3ac87145")]
            public virtual Ranorex.Button BtnAddPerson
            {
                get
                {
                    return _btnaddpersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnAddPerson item info.
            /// </summary>
            [RepositoryItemInfo("c4722e95-d82d-4899-a215-558b3ac87145")]
            public virtual RepoItemInfo BtnAddPersonInfo
            {
                get
                {
                    return _btnaddpersonInfo;
                }
            }

            /// <summary>
            /// The SelectGender item.
            /// </summary>
            [RepositoryItem("4f1e9f80-1ccf-434f-94d2-71ba10c667f3")]
            public virtual Ranorex.RadioButton SelectGender
            {
                get
                {
                    return _selectgenderInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The SelectGender item info.
            /// </summary>
            [RepositoryItemInfo("4f1e9f80-1ccf-434f-94d2-71ba10c667f3")]
            public virtual RepoItemInfo SelectGenderInfo
            {
                get
                {
                    return _selectgenderInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("d1cabd3d-c174-4f6b-9162-92da0f9715e8")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("d1cabd3d-c174-4f6b-9162-92da0f9715e8")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("1f2fb46b-183a-4669-844d-5111d39a7bc0")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("1f2fb46b-183a-4669-844d-5111d39a7bc0")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Age item.
            /// </summary>
            [RepositoryItem("888b637e-5f7c-412f-b242-861ad471471e")]
            public virtual Ranorex.Text Age
            {
                get
                {
                    return _ageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Age item info.
            /// </summary>
            [RepositoryItemInfo("888b637e-5f7c-412f-b242-861ad471471e")]
            public virtual RepoItemInfo AgeInfo
            {
                get
                {
                    return _ageInfo;
                }
            }

            /// <summary>
            /// The TxtTopDBEntry item.
            /// </summary>
            [RepositoryItem("7ea59416-18ba-4fbc-afe2-fbc54a8bab71")]
            public virtual Ranorex.ListItem TxtTopDBEntry
            {
                get
                {
                    return _txttopdbentryInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The TxtTopDBEntry item info.
            /// </summary>
            [RepositoryItemInfo("7ea59416-18ba-4fbc-afe2-fbc54a8bab71")]
            public virtual RepoItemInfo TxtTopDBEntryInfo
            {
                get
                {
                    return _txttopdbentryInfo;
                }
            }

            /// <summary>
            /// The DB_Counter item.
            /// </summary>
            [RepositoryItem("b7165316-6e00-4cbf-946f-533a28fdf096")]
            public virtual Ranorex.Text DB_Counter
            {
                get
                {
                    return _db_counterInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The DB_Counter item info.
            /// </summary>
            [RepositoryItemInfo("b7165316-6e00-4cbf-946f-533a28fdf096")]
            public virtual RepoItemInfo DB_CounterInfo
            {
                get
                {
                    return _db_counterInfo;
                }
            }
        }

        /// <summary>
        /// The DepartmentListAppFolder folder.
        /// </summary>
        [RepositoryFolder("1e8b078d-8f4f-4f00-8d6c-712330c43341")]
        public partial class DepartmentListAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selectdepartmentInfo;

            /// <summary>
            /// Creates a new DepartmentList  folder.
            /// </summary>
            public DepartmentListAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DepartmentList", "/list[@controlid='1000']", parentFolder, 30000, null, true, "1e8b078d-8f4f-4f00-8d6c-712330c43341", "")
            {
                _selectdepartmentInfo = new RepoItemInfo(this, "SelectDepartment", "listitem[@text=$varDepartment]", "", 30000, null, "f13d6dfd-10b3-4e58-a791-f226c32e510a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1e8b078d-8f4f-4f00-8d6c-712330c43341")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1e8b078d-8f4f-4f00-8d6c-712330c43341")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SelectDepartment item.
            /// </summary>
            [RepositoryItem("f13d6dfd-10b3-4e58-a791-f226c32e510a")]
            public virtual Ranorex.ListItem SelectDepartment
            {
                get
                {
                    return _selectdepartmentInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SelectDepartment item info.
            /// </summary>
            [RepositoryItemInfo("f13d6dfd-10b3-4e58-a791-f226c32e510a")]
            public virtual RepoItemInfo SelectDepartmentInfo
            {
                get
                {
                    return _selectdepartmentInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
